### ISSUE TITLE
BZY_Coloborate

### ISSUE THREAD

**Issue by belozersky01** [MessirVoland/Ely#7]
- Дим, где последняя сборка?

**Comment by belozersky01** [comment]
- Дим, зип-файл подошел?

**Comment by belozersky01** [comment]
- Вить. 
1. Один шрифт
2. Иконки
3. ZIP
4. Разберись с ГХ.

**Comment by belozersky01** [comment]
Он здесь вообще есть? 
В этом софте есть уведомления? 
Блять

**Comment by Viktornow** [comment]
Ку-ку

**Comment by MessirVoland** [comment]
есть на почту

**Comment by MessirVoland** [comment]
Добавил @Viktornow как колоборатора, уведомелние пришло на почту и его надо подтвердить.

**Comment by Viktornow** [comment]
Кажется подтвердил

**Comment by MessirVoland** [comment]
Ну тогда с проблемой колобоарций мы разобрались.
